version: '3.8'

services:
  greetings-app-dev:
    build: .
    image: kristelj/python-greetings-app:latest
    container_name: python-greetings-app-dev
    ports:
      - 7001:3000
  greetings-app-stg:
    build: .
    image: kristelj/python-greetings-app:latest
    container_name: python-greetings-app-stg
    ports:
      - 7002:3000
  greetings-app-prod:
    build: .
    image: kristelj/python-greetings-app:latest
    container_name: python-greetings-app-prod
    ports:
      - 7003:3000